apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels: 
    name: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: crud-app
  template:
    metadata:
      labels:
        name: crud-app
    spec:
      containers:
        - name: crud-app
          image: crud_app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env: 
          - name: db_address
            value: "postgres-service"
          - name: db_username
            value: "postgres" 
          - name: db_name
            value: "postgres"
          - name: db_password
            valueFrom:
              secretKeyRef: 
                name: app-secret
                key: db_password
