apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: crud-app
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
  selector:
    name: crud-app
