apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels: 
    name: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: crud-app
  template:
    metadata:
      labels:
        name: crud-app
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env: 
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: postgres 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: app-secret
                key: db_password
    
