apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: crud-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
  selector:
    name: crud-app
